-- 뉴스 게시판 테이블 생성 (MySQL) - 이미지 지원
CREATE TABLE IF NOT EXISTS news (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL COMMENT '제목',
  content TEXT DEFAULT NULL COMMENT '내용',
  writer VARCHAR(255) DEFAULT NULL COMMENT '작성자',
  image_url VARCHAR(500) DEFAULT NULL COMMENT '대표 이미지 경로',
  images JSON DEFAULT NULL COMMENT '추가 이미지 경로 배열',
  view_count INT NOT NULL DEFAULT 0,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
