-- 공지사항 테이블 생성 (MySQL)
CREATE TABLE IF NOT EXISTS notices (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL COMMENT '제목',
  content TEXT DEFAULT NULL COMMENT '내용',
  writer VARCHAR(255) DEFAULT NULL COMMENT '작성자',
  is_pinned TINYINT NOT NULL DEFAULT 0 COMMENT '상단 고정 (1: 고정)',
  view_count INT NOT NULL DEFAULT 0,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
