-- 견적문의 테이블 생성 (MySQL)
CREATE TABLE IF NOT EXISTS quote_inquiries (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL COMMENT '문의자명',
  contact VARCHAR(100) DEFAULT NULL COMMENT '연락처',
  company VARCHAR(100) DEFAULT NULL COMMENT '회사명',
  content TEXT DEFAULT NULL COMMENT '문의 내용',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '처리상태',
  is_deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
